In [1]:
from dotenv import load_dotenv
import os

load_dotenv()

token = os.getenv("KAGGLE_API_TOKEN")
print(token)

KGAT_eedd9991996e18c33926abd0f0d42490

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("robikscube/hourly-energy-consumption")

print("Path to dataset files:", path)

c:\Users\yashs\OneDrive\Desktop\Learning - post job\Time Series Forecasting\tsf_environ\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\yashs\.cache\kagglehub\datasets\robikscube\hourly-energy-consumption\3.archive...

100%|██████████| 11.4M/11.4M [00:02<00:00, 4.71MB/s]

Extracting files...

Path to dataset files: C:\Users\yashs\.cache\kagglehub\datasets\robikscube\hourly-energy-consumption\versions\3

In [ ]:
import os

full_file_path = 
for file in os.listdir(path):
    if file.endswith(".csv"):
        full_path = os.path.join(path, file)
        print(full_path)

C:\Users\yashs\.cache\kagglehub\datasets\robikscube\hourly-energy-consumption\versions\3\AEP_hourly.csv
C:\Users\yashs\.cache\kagglehub\datasets\robikscube\hourly-energy-consumption\versions\3\COMED_hourly.csv
C:\Users\yashs\.cache\kagglehub\datasets\robikscube\hourly-energy-consumption\versions\3\DAYTON_hourly.csv
C:\Users\yashs\.cache\kagglehub\datasets\robikscube\hourly-energy-consumption\versions\3\DEOK_hourly.csv
C:\Users\yashs\.cache\kagglehub\datasets\robikscube\hourly-energy-consumption\versions\3\DOM_hourly.csv
C:\Users\yashs\.cache\kagglehub\datasets\robikscube\hourly-energy-consumption\versions\3\DUQ_hourly.csv
C:\Users\yashs\.cache\kagglehub\datasets\robikscube\hourly-energy-consumption\versions\3\EKPC_hourly.csv
C:\Users\yashs\.cache\kagglehub\datasets\robikscube\hourly-energy-consumption\versions\3\FE_hourly.csv
C:\Users\yashs\.cache\kagglehub\datasets\robikscube\hourly-energy-consumption\versions\3\NI_hourly.csv
C:\Users\yashs\.cache\kagglehub\datasets\robikscube\hourly-energy-consumption\versions\3\PJME_hourly.csv
C:\Users\yashs\.cache\kagglehub\datasets\robikscube\hourly-energy-consumption\versions\3\PJMW_hourly.csv
C:\Users\yashs\.cache\kagglehub\datasets\robikscube\hourly-energy-consumption\versions\3\pjm_hourly_est.csv
C:\Users\yashs\.cache\kagglehub\datasets\robikscube\hourly-energy-consumption\versions\3\PJM_Load_hourly.csv

In [4]:
import pandas as pd

df = pd.read_csv(os.path.join(path, files[0]))
df.head()

              Datetime   AEP_MW
0  2004-12-31 01:00:00  13478.0
1  2004-12-31 02:00:00  12865.0
2  2004-12-31 03:00:00  12577.0
3  2004-12-31 04:00:00  12517.0
4  2004-12-31 05:00:00  12670.0

In [8]:
# Convert datetime into a numerical seconds timestamp object 
# (tells you the date/time in seconds)
df["Datetime"] = pd.to_datetime(df["Datetime"])
import numpy as np
timestamp_s = df['Datetime'].map(pd.Timestamp.timestamp)

# Get the number of seconds for each time period
day = 24*60*60
week = day*7
year = day*(365.2425)

# Transform using sin and cos
# Time of day
df['Day_sin'] = np.sin(timestamp_s * (2 * np.pi / day))
df['Day_cos'] = np.cos(timestamp_s * (2 * np.pi / day))

# Time of week
df['Week_sin'] = np.sin(timestamp_s * (2 * np.pi / week))
df['Week_cos'] = np.cos(timestamp_s * (2 * np.pi / week))

# Time of year
df['Year_sin'] = np.sin(timestamp_s * (2 * np.pi / year))
df['Year_cos'] = np.cos(timestamp_s * (2 * np.pi / year))

In [9]:
df.head()

,Datetime,AEP_MW,Day_sin,Day_cos,Week_sin,Week_cos,Year_sin,Year_cos
0,2004-12-31 01:00:00,13478.0,0.258819,0.965926,0.804598,0.593820,-0.007669,0.999971
1,2004-12-31 02:00:00,12865.0,0.500000,0.866025,0.826239,0.563320,-0.006953,0.999976
2,2004-12-31 03:00:00,12577.0,0.707107,0.707107,0.846724,0.532032,-0.006236,0.999981
3,2004-12-31 04:00:00,12517.0,0.866025,0.500000,0.866025,0.500000,-0.005519,0.999985
4,2004-12-31 05:00:00,12670.0,0.965926,0.258819,0.884115,0.467269,-0.004802,0.999988